### ISSUE TITLE
HTTPS required for security

### ISSUE THREAD

**Issue by isaiahstjohn** [asehmi/auth-simple-for-streamlit#2]
Correct me if I'm wrong, but this solution will not be secure unless it is used over HTTPS. I feel like that should be called out in the README.

**Comment by fredzannarbor** [comment]
+1

**Comment by asehmi** [comment]
No, it is secure for user setup if you run the admin app directly, usually in your D/C. In a production situation, when (and if) you want to access the admin panel via your main app, then you'd be running over HTTPS, e.g. in Streamlit online. Also, as Python code is run on the Streamlit server, the credential encryption and verification is done on the server too.

You can't really harden the setup of user credentials via client-side text entry in an HTTP scenario unless you're using JS, which would require a custom component text box, and some form of shared secret between server and client, which leads to more issues. That's why you should just use HTTPS always, and probably not use this solution, but my Auth0 authentication component.

Note, in general use the user logs in (over HTTPS) and only a success token is sent back to the Streamlit client.
