### ISSUE TITLE
How to upload .env

### ISSUE THREAD

**Issue by tom-doerr** [asehmi/auth-simple-for-streamlit#4]
How can I upload the configuration to Streamlit without publishing them on GitHub?

**Comment by asehmi** [comment]
I'm using dotenv which reads the .env file and puts the variables into the app's environment. I think the simplest thing would be to replace these lines in env.py...
```
ENV_FILE = find_dotenv()
if ENV_FILE:
    load_dotenv(ENV_FILE)
```
...with a small amount of code that reads the values from `.streamlit/secrets.toml` and places them into the app's environment. Then the rest of the app should just work. Note, you will create `secrets.toml` at the time you deploy the app to Streamlit online.

**Comment by Davis782** [comment]
Nice post.  Since this last update I believe the Streamlit platform allows for Sharing with a unique URL via Github Repository.  Do you have a protocal for using this solution when you have a Googlesheet API where the Key_File must be placed in the secret folder ?  Please provide an example if possible. 

I was having the current issue with the following......

"Deploy the demo app on "Streamlit Sharing" and use it's "secrets store" instead of my .env solution."

I would love to see how you would approach the above.  It appears there is a challenge with pointing a file as per the docs, whereas they show how to push variables, but not files.  Please advise.  I imagine there is easy pythonic solution to this.  Otherwise, I believe your solution would be highly considered.

Regards

**Comment by asehmi** [comment]
Apart from manually copying and pasting all secrets into the dialog box that pops up when you deploy a Streamlit cloud app and making the changes to load `.streamlit/secrets.toml` into the running app's environment, I don't know what else to do. In other clouds (Heroku, Azure, AWS, etc.) you'd use a SSH terminal or proprietary CLI tool (for your cloud) to connect to the running container and upload the `.env` file that way. If you have a secure database, you could use that to store your secrets, but then you need to store your secret DB connection, and you're back to square one! Perhaps you can encrypt the .env file, and store the decryption key in `.streamlit/secrets.toml`. That way you only need to copy/paste one secret at the time you deploy your Streamlit cloud app. I implemented some encryption/decryption algorithms in this project, so you can use that code to do the job.

Sorry can't be of more help.

**Comment by Davis782** [comment]
Morning Arvindra,
Arvindra quote."Sorry can't be of more help" ?
This is an excellent reply to this issue and I appreciate you giving it some thought.  I thought I was missing something and I realized how I was with your help.I can at a minimum proceed with a better understanding of how to move forward.
Thank you.
Davis Rogers M.S.M.E.
Class A BLD
***@***.***


-----Original Message-----
